name: Build & publish examples
env:
  CLONE_PATH:    ${{ github.workspace }}
  EXAMPLES_BOOK: ${{ github.workspace }}/examples/_build/html
on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # We only need to run tools with a single python version.  Ideally
      # this will be the latest version of python used in the action.
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    steps:
    ##-- General Setup Steps
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup python with tox
      run: ./.github/workflows/setup_tox_github_action.sh

    ## -- Build all documentation
    - name: Build Examples Jupyterbook
      run: |
        pushd $CLONE_PATH/stuff_pypkg
        tox -r -e examples
        popd

    ##-- Archive all documentation products
    - name: Archive stuff examples Jupyterbook
      uses: actions/upload-pages-artifact@v3
      with:
        path: "./examples/_build/html"

  ##-- Publish all documentation
  publish:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Publish Examples Jupyterbook
      id: deployment
      uses: actions/deploy-pages@v3
