name: Build documentation
env:
  CLONE_PATH:    ${{ github.workspace }}
  PDF_DOCS:      ${{ github.workspace }}/docs/build_pdf
  HTML_DOCS:     ${{ github.workspace }}/docs/build_html
  EXAMPLES_BOOK: ${{ github.workspace }}/examples/_build
on:
  push:
    branches:
      - main
workflow_dispatch:

jobs:
  build_docs:
    runs-on: ${{ matrix.os }}
    strategy:
      # We only need to run tools with a single python version.  Ideally
      # this will be the latest version of python used in the action.
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    steps:
    ##-- General Setup Steps
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup python with tox
      run: ./.github/workflows/setup_tox_github_action.sh

    - name: Build examples
      run: |
        pushd $CLONE_PATH/stuff_pypkg
        tox -r -e examples
        tox -r -e html,pdf
        popd

    ##-- Publish sphinx docs
    - name: Archive stuff examples Jupyterbook
      uses: actions/upload-artifact@v4
      with:
        name: stuff-examples
        path: |
          ${{ env.EXAMPLES_BOOK }}

    - name: Archive stuff documentation
      uses: actions/upload-artifact@v4
      with:
        name: stuff-docs
        path: |
          ${{ env.PDF_DOCS }}
          ${{ env.HTML_DOCS }}
